name: Compile C++ to WebAssembly and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Zmień na swoją główną gałąź, np. master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache Emscripten SDK
        uses: actions/cache@v4
        with:
          path: emsdk
          key: emsdk-${{ runner.os }}-v1

      - name: Cache Emscripten build cache
        uses: actions/cache@v4
        with:
          path: ~/.emscripten_cache
          key: emscripten-cache-${{ runner.os }}-v1

      - name: Install Emscripten and compile
        run: |
          git clone https://github.com/emscripten-core/emsdk.git || true
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
          mkdir -p dist
          emcc snakeT.c \
            -s WASM=1 \
            -s USE_SDL=2 \
            -s USE_SDL_IMAGE=2 \
            -s SDL2_IMAGE_FORMATS='["png"]' \
            -s USE_SDL_TTF=2 \
            -s USE_WEBGL2=1 \
            -s MAX_WEBGL_VERSION=2 \
            -s MIN_WEBGL_VERSION=2 \
            --preload-file assets \
            -o dist/index.html
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
